name: trys_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.1
  sqflite: ^2.3.3+1
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  super_awesome_dialog: ^1.1.0
  awesome_dialog: ^3.2.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.1
  rive_common: ^0.4.7
  rive: ^0.13.3
  flutter_android_developer_mode: ^1.0.0
  flutter_spinkit: ^5.2.1
  open_street_map_search_and_pick: ^0.1.1
  location_picker_flutter_map: ^3.0.1
  location: ^6.0.2
  http: ^1.2.1
  dio: ^5.4.3+1
  google_maps_flutter: ^2.6.1
  background_fetch: ^1.3.4
  flutter_background_geolocation: ^4.15.2
  url_launcher: ^6.2.6
  geocoding: ^3.0.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_typeahead: ^5.2.0
  dartz: ^0.10.1
  flutter_stripe: ^10.1.1
  flutter_local_notifications: ^17.1.2
  flutter_stripe_payment: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages