// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Jz7ut7SBR7w-_PzgsSV2eJgRx31553w',
    appId: '1:556813693337:web:a3603ee9625fbd1566e308',
    messagingSenderId: '556813693337',
    projectId: 'flutterlogin-668f6',
    authDomain: 'flutterlogin-668f6.firebaseapp.com',
    storageBucket: 'flutterlogin-668f6.appspot.com',
    measurementId: 'G-CJ2H3EYXBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaYEcntQRBssgV9YDTFcml8PZkS9oGSVY',
    appId: '1:556813693337:android:8f908fa7e451585966e308',
    messagingSenderId: '556813693337',
    projectId: 'flutterlogin-668f6',
    storageBucket: 'flutterlogin-668f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFsol7Mu04KHNEyW9MENrWjG9ajNkiDc',
    appId: '1:556813693337:ios:f95e75e8380150a766e308',
    messagingSenderId: '556813693337',
    projectId: 'flutterlogin-668f6',
    storageBucket: 'flutterlogin-668f6.appspot.com',
    iosBundleId: 'com.example.udemyflutterone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwFsol7Mu04KHNEyW9MENrWjG9ajNkiDc',
    appId: '1:556813693337:ios:f95e75e8380150a766e308',
    messagingSenderId: '556813693337',
    projectId: 'flutterlogin-668f6',
    storageBucket: 'flutterlogin-668f6.appspot.com',
    iosBundleId: 'com.example.udemyflutterone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Jz7ut7SBR7w-_PzgsSV2eJgRx31553w',
    appId: '1:556813693337:web:21d518caac841ac366e308',
    messagingSenderId: '556813693337',
    projectId: 'flutterlogin-668f6',
    authDomain: 'flutterlogin-668f6.firebaseapp.com',
    storageBucket: 'flutterlogin-668f6.appspot.com',
    measurementId: 'G-1VLSRX8FY4',
  );
}
